name: Run Discord Movie Bot

on:
  schedule:
    - cron: "0 12 * * *"   # Runs every day at 12:00 UTC
  workflow_dispatch:       # Allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      # TEST_MODE is set differently depending on trigger
      TEST_MODE: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
