name: Daily Discord Movie Bot

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch: # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install discord.py requests

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
        run: python bot.py
